import type { FMCState } from '../types/fmc';
import { AirbusFCUState, AutoflightTruthState } from '../autopilot/autopilotTypes';

export function createBaseState(overrides: Partial<FMCState> = {}): FMCState {
  return {
    aircraft: 'BOEING_737',
    page: 'IDENT',
    autopilot: {
      boeing: {
        courseL: 0,
        courseR: 0,
        speed: 250,
        mach: null,
        heading: 0,
        altitude: 0,
        verticalSpeed: null,
        fdLeft: false,
        fdRight: false,
        autothrottleArm: false,
        n1: false,
        speedMode: false,
        lnav: false,
        vnav: false,
        lvlChg: false,
        hdgSel: false,
        vorLoc: false,
        app: false,
        altHold: false,
        vs: false,
        cmdA: false,
        cmdB: false,
        cwsA: false,
        cwsB: false,
      },
      airbus: {
        speed: 250,
        speedManaged: false,
        heading: 0,
        headingManaged: false,
        altitude: 0,
        altitudeManaged: false,
        verticalSpeed: null,
        fpa: null,
        fd1: false,
        fd2: false,
        athr: false,
        ap1: false,
        ap2: false,
        loc: false,
        appr: false,
        exped: false,
        hdgTrkMode: 'HDG_VS',
        metricAltitude: false,
        speedMachMode: 'SPD',
      } as AirbusFCUState,
      truth: {
        lateralActive: 'OFF',
        verticalActive: 'OFF',
        thrustActive: 'OFF',
        autopilotStatus: 'OFF',
        lastModeChangeTimestamps: {
          thrust: 0,
          lateral: 0,
          vertical: 0,
        },
      } as AutoflightTruthState,
    },
    currentPage: 'IDENT',
    pageHistory: [],
    scratchpad: '',
    scratchpadError: null,
    demoMode: false,
    ident: { aircraftType: '737-800', engRating: '26K', navDataVersion: 'FMC21A1', opProgram: '2247662-03' },
    position: {
      refAirport: '',
      gate: '',
      lat: 0,
      lon: 0,
      irsState: 'NAV',
      irsTimeRemaining: 0,
      irsAlignmentProgress: 100,
    },
    sensors: [
      { source: 'GPS', available: true, positionErrorNm: 0.05 },
      { source: 'IRS', available: true, positionErrorNm: 2.0 },
    ],
    navPerformance: {
      anpNm: 0.05,
      rnpNm: 2.0,
      anp: 0.05,
      rnp: 2.0,
      rnpManual: false,
      activeSource: 'GPS',
      phase: 'ENROUTE',
      xteNm: 0,
    },
    activeNavSource: 'GPS',
    alerts: [],
    signsOn: false,
    windowsLocked: false,
    posPageIndex: 0,
    performance: { crzAlt: 0, costIndex: 0, zfw: 0, fuel: 0, cg: 0, reserve: 0, grossWeight: 0 },
    takeoff: {
      runway: '',
      toMode: 'TO',
      assumedTemp: 0,
      v1: 0,
      vr: 0,
      v2: 0,
      trim: 0,
      oat: 0,
      windDir: 0,
      windSpeed: 0,
      qnh: 0,
    },
    landing: { runway: '', flaps: '', vref: 0, ilsFrequency: '', course: 0 },
    route: { origin: '', destination: '', flightNumber: '', companyRoute: '', routeString: '' },
    flightPlan: { origin: '', destination: '', flightNumber: '', route: '', waypoints: [] },
    pendingRoute: null,
    pendingFlightPlan: null,
    isModified: false,
    execLit: false,
    msgLight: false,
    mode: 'STANDBY',
    connectionStatus: 'DISCONNECTED',
    connectionMode: 'STANDALONE',
    legsPageIndex: 0,
    legsPageCount: 1,
    depArrSubPage: 'DEP',
    rteSubPage: 0,
    takeoffRefPageIndex: 0,
    hold: { fix: '', inboundCourse: 0, legTime: 1.0, legDist: 0, direction: 'R' },
    holdPending: null,
    fix: { refFix: '', radial: 0, distance: 0 },
    fixEntries: [
      { refFix: '', radial: 0, distance: 0 },
      { refFix: '', radial: 0, distance: 0 },
    ],
    deleteMode: false,
    editWaypointIndex: null,
    aircraftState: null,
    connectedAircraft: null,
    connectedAircraftType: null,
    connectedCapabilities: [],
    lastError: null,
    simVariables: {},
    failureMessage: null,
    externalDisplayData: null,
    atsu: { messages: [], pendingUplink: null },
    flightPhase: 'PREFLIGHT',
    scratchpadMessages: [],
    airbusFmgc: {
      fm1Healthy: true,
      fm2Healthy: true,
      mode: 'DUAL',
      leftMcduSource: 'FMGC1',
      rightMcduSource: 'FMGC1',
    },
    trainingActive: false,
    trainingScenario: null,
    trainingEngine: null,
    trainingMistakes: [],
    trainingScore: null,
    trainingStepIndex: 0,
    trainingCompleted: false,
    activeScenario: null,
    flightPathHistory: [],
    debriefMode: false,
    isReportVisible: false,
    tutorialHintLevel: 0,
    tutorialHintTimer: null,
    efisL: {
      mode: 'MAP',
      range: 40,
      centered: false,
      side: 'L',
      overlays: {
        wpt: false,
        arpt: false,
        sta: false,
        data: false,
        pos: false,
        terr: false,
        wxr: false,
        tfc: false,
        cstr: false,
      },
    },
    efisR: {
      mode: 'MAP',
      range: 40,
      centered: false,
      side: 'R',
      overlays: {
        wpt: false,
        arpt: false,
        sta: false,
        data: false,
        pos: false,
        terr: false,
        wxr: false,
        tfc: false,
        cstr: false,
      },
    },
    brightness: 100,
    cockpitMode: false,
    cockpitLayoutMode: 'fmc-focus',
    hiddenPanels: ['nd', 'pfd', 'autoflight', 'checklist', 'connection', 'settings'],
    pinnedPanels: [],
    focusedPanel: null,
    latency: 0,
    sessionStartTime: null,
    radios: {
      vor1: '113.90',
      vor2: '115.70',
      adf1: '342',
    },
    tutorialActive: false,
    tutorialCompleted: false,
    tutorialStepIndex: 0,
    tutorialScenario: null,
    tutorialStartTime: null,
    tutorialErrors: 0,
    tutorialHint: null,
    tutorialSkipAvailable: false,
    tutorialHighlight: null,
    tutorialConfidence: null,
    selectedPlanWaypointIndex: null,
    trafficTargets: [],
    selectedMessageId: null,
    gpwsAlert: 'NONE',
    tcasAlert: false,
    ...overrides,
  };
}
